// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignUpResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Version              float32  `protobuf:"fixed32,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignUpResponse) Reset()         { *m = SignUpResponse{} }
func (m *SignUpResponse) String() string { return proto.CompactTextString(m) }
func (*SignUpResponse) ProtoMessage()    {}
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *SignUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignUpResponse.Unmarshal(m, b)
}
func (m *SignUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignUpResponse.Marshal(b, m, deterministic)
}
func (m *SignUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignUpResponse.Merge(m, src)
}
func (m *SignUpResponse) XXX_Size() int {
	return xxx_messageInfo_SignUpResponse.Size(m)
}
func (m *SignUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignUpResponse proto.InternalMessageInfo

func (m *SignUpResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SignUpResponse) GetVersion() float32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type TosChat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TosChat) Reset()         { *m = TosChat{} }
func (m *TosChat) String() string { return proto.CompactTextString(m) }
func (*TosChat) ProtoMessage()    {}
func (*TosChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *TosChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TosChat.Unmarshal(m, b)
}
func (m *TosChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TosChat.Marshal(b, m, deterministic)
}
func (m *TosChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TosChat.Merge(m, src)
}
func (m *TosChat) XXX_Size() int {
	return xxx_messageInfo_TosChat.Size(m)
}
func (m *TosChat) XXX_DiscardUnknown() {
	xxx_messageInfo_TosChat.DiscardUnknown(m)
}

var xxx_messageInfo_TosChat proto.InternalMessageInfo

func (m *TosChat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TosChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type TocChat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TocChat) Reset()         { *m = TocChat{} }
func (m *TocChat) String() string { return proto.CompactTextString(m) }
func (*TocChat) ProtoMessage()    {}
func (*TocChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *TocChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TocChat.Unmarshal(m, b)
}
func (m *TocChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TocChat.Marshal(b, m, deterministic)
}
func (m *TocChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TocChat.Merge(m, src)
}
func (m *TocChat) XXX_Size() int {
	return xxx_messageInfo_TocChat.Size(m)
}
func (m *TocChat) XXX_DiscardUnknown() {
	xxx_messageInfo_TocChat.DiscardUnknown(m)
}

var xxx_messageInfo_TocChat proto.InternalMessageInfo

func (m *TocChat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TocChat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Login struct {
	PlayerID             int32    `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}
func (*Login) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *Login) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Login.Unmarshal(m, b)
}
func (m *Login) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Login.Marshal(b, m, deterministic)
}
func (m *Login) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Login.Merge(m, src)
}
func (m *Login) XXX_Size() int {
	return xxx_messageInfo_Login.Size(m)
}
func (m *Login) XXX_DiscardUnknown() {
	xxx_messageInfo_Login.DiscardUnknown(m)
}

var xxx_messageInfo_Login proto.InternalMessageInfo

func (m *Login) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *Login) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PlayerBaseInfo struct {
	PlayerID             int32    `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerBaseInfo) Reset()         { *m = PlayerBaseInfo{} }
func (m *PlayerBaseInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerBaseInfo) ProtoMessage()    {}
func (*PlayerBaseInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *PlayerBaseInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerBaseInfo.Unmarshal(m, b)
}
func (m *PlayerBaseInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerBaseInfo.Marshal(b, m, deterministic)
}
func (m *PlayerBaseInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerBaseInfo.Merge(m, src)
}
func (m *PlayerBaseInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerBaseInfo.Size(m)
}
func (m *PlayerBaseInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerBaseInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerBaseInfo proto.InternalMessageInfo

func (m *PlayerBaseInfo) GetPlayerID() int32 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *PlayerBaseInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginSuccessfull struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginSuccessfull) Reset()         { *m = LoginSuccessfull{} }
func (m *LoginSuccessfull) String() string { return proto.CompactTextString(m) }
func (*LoginSuccessfull) ProtoMessage()    {}
func (*LoginSuccessfull) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *LoginSuccessfull) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSuccessfull.Unmarshal(m, b)
}
func (m *LoginSuccessfull) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSuccessfull.Marshal(b, m, deterministic)
}
func (m *LoginSuccessfull) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSuccessfull.Merge(m, src)
}
func (m *LoginSuccessfull) XXX_Size() int {
	return xxx_messageInfo_LoginSuccessfull.Size(m)
}
func (m *LoginSuccessfull) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSuccessfull.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSuccessfull proto.InternalMessageInfo

type LoginFaild struct {
	RspHead              *RspHead `protobuf:"bytes,1,opt,name=rspHead,proto3" json:"rspHead,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginFaild) Reset()         { *m = LoginFaild{} }
func (m *LoginFaild) String() string { return proto.CompactTextString(m) }
func (*LoginFaild) ProtoMessage()    {}
func (*LoginFaild) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *LoginFaild) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginFaild.Unmarshal(m, b)
}
func (m *LoginFaild) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginFaild.Marshal(b, m, deterministic)
}
func (m *LoginFaild) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginFaild.Merge(m, src)
}
func (m *LoginFaild) XXX_Size() int {
	return xxx_messageInfo_LoginFaild.Size(m)
}
func (m *LoginFaild) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginFaild.DiscardUnknown(m)
}

var xxx_messageInfo_LoginFaild proto.InternalMessageInfo

func (m *LoginFaild) GetRspHead() *RspHead {
	if m != nil {
		return m.RspHead
	}
	return nil
}

func init() {
	proto.RegisterType((*SignUpResponse)(nil), "msg.SignUpResponse")
	proto.RegisterType((*TosChat)(nil), "msg.TosChat")
	proto.RegisterType((*TocChat)(nil), "msg.TocChat")
	proto.RegisterType((*Login)(nil), "msg.Login")
	proto.RegisterType((*PlayerBaseInfo)(nil), "msg.PlayerBaseInfo")
	proto.RegisterType((*LoginSuccessfull)(nil), "msg.LoginSuccessfull")
	proto.RegisterType((*LoginFaild)(nil), "msg.LoginFaild")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0x74, 0xd6, 0xbe, 0x8d, 0x21, 0x39, 0x95, 0xe1, 0x61, 0xf4, 0x20, 0x3b, 0xf5,
	0xa0, 0x82, 0x57, 0x71, 0x22, 0x1b, 0x88, 0x48, 0xa6, 0x1f, 0x20, 0xa6, 0x6f, 0xb5, 0x90, 0xe4,
	0x95, 0xbc, 0x4e, 0xf0, 0xdb, 0x4b, 0x93, 0x55, 0xcf, 0xee, 0xf6, 0xfe, 0xff, 0xc7, 0xef, 0x97,
	0x84, 0xc0, 0xc4, 0x50, 0xdd, 0xb8, 0xb2, 0xf5, 0xd4, 0x91, 0x38, 0xb1, 0x5c, 0xcf, 0xa7, 0x9a,
	0xac, 0xa5, 0x43, 0x55, 0xac, 0x61, 0xb6, 0x6d, 0x6a, 0xf7, 0xde, 0x4a, 0xe4, 0x96, 0x1c, 0xa3,
	0xb8, 0x84, 0x0c, 0xbd, 0x27, 0xbf, 0xa2, 0x0a, 0xf3, 0x64, 0x91, 0x2c, 0xc7, 0xf2, 0xaf, 0x10,
	0x39, 0xa4, 0x5f, 0xe8, 0xb9, 0x21, 0x97, 0x8f, 0x16, 0xc9, 0x72, 0x24, 0x87, 0x58, 0xdc, 0x41,
	0xfa, 0x46, 0xbc, 0xfa, 0x54, 0x9d, 0x10, 0x70, 0xea, 0x94, 0x8d, 0x74, 0x26, 0xc3, 0xdc, 0x83,
	0x9a, 0x5c, 0x87, 0xae, 0x0b, 0x60, 0x26, 0x87, 0x18, 0x41, 0x7d, 0x14, 0x38, 0x7e, 0xee, 0x5f,
	0x27, 0xe6, 0x70, 0xfe, 0x6a, 0xd4, 0x37, 0xfa, 0xcd, 0xe3, 0xe1, 0xc6, 0xbf, 0xb9, 0x57, 0xbe,
	0xf4, 0xca, 0xc8, 0x86, 0xb9, 0xb8, 0x87, 0x59, 0xdc, 0x3f, 0x28, 0xc6, 0x8d, 0xdb, 0xd1, 0xbf,
	0x0d, 0x02, 0x2e, 0xc2, 0xd1, 0xdb, 0xbd, 0xd6, 0xc8, 0xbc, 0xdb, 0x1b, 0x53, 0xdc, 0x02, 0x84,
	0xee, 0x49, 0x35, 0xa6, 0x12, 0x57, 0x90, 0x7a, 0x6e, 0xd7, 0xa8, 0xaa, 0x20, 0x9c, 0x5c, 0x4f,
	0x4b, 0xcb, 0x75, 0x29, 0x63, 0x27, 0x87, 0xe5, 0xc7, 0x59, 0xf8, 0x87, 0x9b, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0x57, 0x09, 0xf5, 0xa9, 0x01, 0x00, 0x00,
}
